### ISSUE TITLE
Don't pollute the global namespace

### ISSUE THREAD

**Issue by OriR** [pd4d10/console-importer#4] opened 2018-12-11 22:27 UTC
Right now when using `$i` it puts the result (when finished) on the global namespace - the window.

I'm proposing that instead it returns a promise (due to the async nature of import) that evaluates with the result of executing the desired imported module.

Something like this
```js
$i('lodash').then(_ => _.toNumber(null));
```

This could also be used with top-level await like this
```js
const _ = await $i('lodash');
_.toNumber(null);
```

This is gives you the control whether or not you want to pollute the global namespace and how.
Plus, now you don't have to know how the internal module exposes itself (`$`, `_`, etc.)

**Comment by pd4d10** [comment] 2022-05-04 06:25
Duplicate of #14

**Closed by pd4d10** 2022-05-04 06:25 UTC
